import {
  BedrockRuntimeClient,
  InvokeModelCommand,
} from '@aws-sdk/client-bedrock-runtime';

const bedrockClient = new BedrockRuntimeClient({
  region: process.env.AWS_REGION || 'us-east-1',
});

/**
 * Represents a single message in the chat conversation history.
 */
interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

const conversationHistory: ChatMessage[] = [];

/**
 * Initiates a chat with the Claude 3 AI model via AWS Bedrock.
 * Maintains conversation history for context.
 *
 * @param {string} userMessage - The message input from the user.
 * @param {string} [context] - Optional context to alter the system prompt (e.g., 'sports').
 * @returns {Promise<string>} The response generated by the AI assistant.
 */
export const chatWithClaude = async (
  userMessage: string,
  context?: string
): Promise<string> => {
  try {
    if (process.env.NODE_ENV === 'test') {
      // simple mock response for tests
      return `mock response to "${userMessage}"`;
    }

    conversationHistory.push({
      role: 'user',
      content: userMessage,
    });

    const systemPrompt =
      context === 'sports'
        ? `You are an expert sports commentator and analyst with deep knowledge of all major sports worldwide. 
         Provide insights about ongoing matches, predictions, player statistics, and interesting facts about sports. 
         Be enthusiastic and engaging in your responses.`
        : 'You are a helpful sports information assistant.';

    const messages = conversationHistory.map((msg) => ({
      role: msg.role,
      content: msg.content,
    }));

    const payload = {
      model: 'claude-3-sonnet-20240229',
      max_tokens: 1024,
      system: systemPrompt,
      messages,
    };

    const command = new InvokeModelCommand({
      modelId: 'anthropic.claude-3-sonnet-20240229',
      body: JSON.stringify(payload),
    });

    const response = await bedrockClient.send(command);
    const responseBody = JSON.parse(new TextDecoder().decode(response.body));
    const assistantMessage = responseBody.content[0].text;

    conversationHistory.push({
      role: 'assistant',
      content: assistantMessage,
    });

    // Keep last 10 messages for context
    if (conversationHistory.length > 20) {
      conversationHistory.splice(0, 2);
    }

    return assistantMessage;
  } catch (error) {
    console.error('Error calling Bedrock:', error);
    throw error;
  }
};

/**
 * Generates an exciting, short commentary summary for a given match.
 *
 * @param {any} matchData - The match details object containing team names, score, etc.
 * @returns {Promise<string>} A 2-3 sentence enthusiastic summary from the AI.
 */
export const generateMatchSummary = async (matchData: any): Promise<string> => {
  try {
    if (process.env.NODE_ENV === 'test') {
      return `Mock summary for ${matchData.homeTeam} vs ${matchData.awayTeam}`;
    }

    const prompt = `Generate a brief, exciting 2-3 sentence commentary for this match:
    ${JSON.stringify(matchData, null, 2)}
    Make it enthusiastic and informative.`;

    const payload = {
      model: 'claude-3-sonnet-20240229',
      max_tokens: 150,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    };

    const command = new InvokeModelCommand({
      modelId: 'anthropic.claude-3-sonnet-20240229',
      body: JSON.stringify(payload),
    });

    const response = await bedrockClient.send(command);
    const responseBody = JSON.parse(new TextDecoder().decode(response.body));
    return responseBody.content[0].text;
  } catch (error) {
    console.error('Error generating summary:', error);
    throw error;
  }
};

/**
 * Retrieves an AI prediction for a specific match.
 * Currently returns a placeholder for future Amazon Forecast integration.
 *
 * @param {string} matchId - The unique identifier of the match.
 * @returns {Promise<any>} An object containing the matchId, prediction string, and a confidence score.
 */
export const getPrediction = async (matchId: string): Promise<any> => {
  try {
    if (process.env.NODE_ENV === 'test') {
      return { matchId, prediction: 'home', confidence: 0.75 };
    }
    // TODO: Integrate with Amazon Forecast
    return {
      matchId,
      prediction: 'To be implemented with Amazon Forecast',
      confidence: 0,
    };
  } catch (error) {
    console.error('Prediction error:', error);
    throw error;
  }
};
