import {
  BedrockRuntimeClient,
  InvokeModelCommand,
} from '@aws-sdk/client-bedrock-runtime';

const bedrockClient = new BedrockRuntimeClient({
  region: process.env.AWS_REGION || 'us-east-1',
});

const BEDROCK_MODEL_ID =
  process.env.BEDROCK_MODEL_ID || 'anthropic.claude-3-sonnet-20240229';

/**
 * Represents a single message in the chat conversation history.
 */
interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

/**
 * Initiates a chat with the Claude AI model via AWS Bedrock.
 * Lambda functions are stateless — pass prior history per-request.
 * Callers that need multi-turn conversations must persist and supply history.
 *
 * @param {string} userMessage - The message input from the user.
 * @param {string} [context] - Optional context to alter the system prompt (e.g., 'sports').
 * @param {ChatMessage[]} [history] - Prior conversation turns (caller-managed).
 * @returns {Promise<string>} The response generated by the AI assistant.
 */
export const chatWithClaude = async (
  userMessage: string,
  context?: string,
  history: ChatMessage[] = []
): Promise<string> => {
  try {
    if (process.env.NODE_ENV === 'test') {
      return `mock response to "${userMessage}"`;
    }

    const messages = [
      ...history,
      { role: 'user' as const, content: userMessage },
    ];

    const systemPrompt =
      context === 'sports'
        ? `You are an expert sports commentator and analyst with deep knowledge of all major sports worldwide.
         Provide insights about ongoing matches, predictions, player statistics, and interesting facts about sports.
         Be enthusiastic and engaging in your responses.`
        : 'You are a helpful sports information assistant.';

    const payload = {
      model: BEDROCK_MODEL_ID.replace('anthropic.', ''),
      max_tokens: 1024,
      system: systemPrompt,
      messages,
    };

    const command = new InvokeModelCommand({
      modelId: BEDROCK_MODEL_ID,
      body: JSON.stringify(payload),
    });

    const response = await bedrockClient.send(command);
    const responseBody = JSON.parse(new TextDecoder().decode(response.body));
    return responseBody.content[0].text;
  } catch (error) {
    console.error('Error calling Bedrock:', error);
    throw error;
  }
};

/**
 * Generates an exciting, short commentary summary for a given match.
 *
 * @param {any} matchData - The match details object containing team names, score, etc.
 * @returns {Promise<string>} A 2-3 sentence enthusiastic summary from the AI.
 */
export const generateMatchSummary = async (matchData: any): Promise<string> => {
  try {
    if (process.env.NODE_ENV === 'test') {
      return `Mock summary for ${matchData.homeTeam} vs ${matchData.awayTeam}`;
    }

    const prompt = `Generate a brief, exciting 2-3 sentence commentary for this match:
    ${JSON.stringify(matchData, null, 2)}
    Make it enthusiastic and informative.`;

    const payload = {
      model: BEDROCK_MODEL_ID.replace('anthropic.', ''),
      max_tokens: 150,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    };

    const command = new InvokeModelCommand({
      modelId: BEDROCK_MODEL_ID,
      body: JSON.stringify(payload),
    });

    const response = await bedrockClient.send(command);
    const responseBody = JSON.parse(new TextDecoder().decode(response.body));
    return responseBody.content[0].text;
  } catch (error) {
    console.error('Error generating summary:', error);
    throw error;
  }
};

/**
 * Retrieves an AI prediction for a specific match.
 * Currently returns a placeholder for future Amazon Forecast integration.
 *
 * @param {string} matchId - The unique identifier of the match.
 * @returns {Promise<any>} An object containing the matchId, prediction string, and a confidence score.
 */
export const getPrediction = async (matchId: string): Promise<any> => {
  try {
    if (process.env.NODE_ENV === 'test') {
      return { matchId, prediction: 'home', confidence: 0.75 };
    }
    // TODO: Integrate with Amazon Forecast
    return {
      matchId,
      prediction: 'To be implemented with Amazon Forecast',
      confidence: 0,
    };
  } catch (error) {
    console.error('Prediction error:', error);
    throw error;
  }
};
